//Given two strings s and t which consist of only lowercase letters.
//
//String t is generated by random shuffling string s and then add one more letter at a random position.
//
//Find the letter that was added in t.
//
//Example:
//
//Input:
//s = "abcd"
//t = "abcde"
//
//Output:
//e
//
//Explanation:
//'e' is the letter that was added.

public class Find_Difference {

	public char findTheDifference(String s, String t) {
        
        /*Map<Character, Integer> s_map = new HashMap<>();
        Map<Character, Integer> t_map = new HashMap<>();
        
        for(int i = 0; i < s.length(); i++)
            s_map.put(s.charAt(i), s_map.getOrDefault(s.charAt(i), 0) + 1);
        
        for(int i = 0; i < t.length(); i++)
            t_map.put(t.charAt(i), t_map.getOrDefault(t.charAt(i), 0) + 1);
        
        for(Map.Entry<Character, Integer> entry : t_map.entrySet()){
            
            char key = entry.getKey();
            int val = entry.getValue();
            
            if(!s_map.containsKey(key))
                return key;
            
            else{
                
                if(s_map.get(key) != val)
                    return key;
            }
        }
        return '@';
        */
        if(s.length() == 0)
            return t.charAt(0);
        
        int r1 = s.charAt(0) - 'a';
        int r2 = t.charAt(0) - 'a';
        
        for(int i= 1; i < s.length(); i++){
            r1 = r1 ^ s.charAt(i) - 'a';
        }
        
        for(int i= 1; i < t.length(); i++){
            r2 = r2 ^ t.charAt(i) - 'a';
        }
        
        int res = r1 ^ r2;
        return (char)(res + 'a');
    }
}
